//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskmvc2_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int id { get; set; }

        [Required]
        public string first_name { get; set; }
        [Required]
        public string last_name { get; set; }
        [Required]
        [EmailAddress]
        public string email { get; set; }
        [RegularExpression(@"^(07)[7-9]{1}[0-9]{7}$", ErrorMessage = "Not a valid Jordanian phone number")]
        [Required]
        public string phone { get; set; }
        [Required]
        [Range(18, 99)]
        public Nullable<int> age { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        public string job_title { get; set; }
        [Required]
        public string Gender { get; set; }
    }
}
