//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvctask5_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class EMPL
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string first_name { get; set; }
        [Required]
        [Display(Name = "last Name")]
        public string last_name { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "EMAIL")]
        public string email { get; set; }
        [RegularExpression(@"^(07)[7-9]{1}[0-9]{7}$", ErrorMessage = "Not a valid Jordanian phone number")]
        [Required]
        [Display(Name = "Phone")]
        public string phone { get; set; }
        [Required]
        [Range(18, 99)]
        [Display(Name = "Age")]
        public Nullable<int> age { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Job Title")]
        public string jop_title { get; set; }
        [Required]
        public Nullable<bool> gender { get; set; }
        //[Required]
        public string img { get; set; }
        [Required]
        public string cv { get; set; }
    }
}
