//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_TASK_7_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat
    {
        public int id { get; set; }
        public string img { get; set; }
        public string description { get; set; }
        public Nullable<int> price { get; set; }
    }
}
